[package]
name = "terminal-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29.1-beta"
simple_logger = "4.2.0"
fontdue = "0.7.3"
softbuffer = "0.3.1"
